name: violin
description: Track your favorite albums
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: "^3.0.0"

dependencies:

  cached_network_image: ^3.2.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  url_launcher: ^6.1.6


dev_dependencies:
  flutter_lints: ^2.0.0

  #dart_code_metrics: ^4.13.0
  flutter_test:
    sdk: flutter
  #json_serializable: ^6.3.1
  #lint: ^1.5.3
  #network_image_mock: ^2.0.1
  #very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
